apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    api-approved.openshift.io: https://github.com/openshift/api/pull/1245
    api.openshift.io/merged-by-featuregates: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/feature-set: TechPreviewNoUpgrade
  name: insightsdatagathers.config.openshift.io
spec:
  group: config.openshift.io
  names:
    kind: InsightsDataGather
    listKind: InsightsDataGatherList
    plural: insightsdatagathers
    singular: insightsdatagather
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: |-
          InsightsDataGather provides data gather configuration options for the the Insights Operator.

          Compatibility level 4: No compatibility is provided, the API can change at any point for any reason. These capabilities should not be used by applications needing long term support.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: spec holds user settable values for configuration
            properties:
              gatherConfig:
                description: |-
                  gatherConfig spec attribute includes all the configuration options related to
                  gathering of the Insights data and its uploading to the ingress.
                properties:
                  dataPolicy:
                    default: None
                    description: |-
                      dataPolicy allows user to enable additional global obfuscation of the IP addresses and base domain
                      in the Insights archive data. Valid values are "None" and "ObfuscateNetworking".
                      When set to None the data is not obfuscated.
                      When set to ObfuscateNetworking the IP addresses and the cluster domain name are obfuscated.
                      When omitted, this means no opinion and the platform is left to choose a reasonable default, which is subject to change over time.
                      The current default is None.
                    enum:
                    - ""
                    - None
                    - ObfuscateNetworking
                    type: string
                  disabledGatherers:
                    description: |-
                      disabledGatherers is a list of gatherers to be excluded from the gathering. All the gatherers can be disabled by providing "all" value.
                      If all the gatherers are disabled, the Insights operator does not gather any data.
                      The particular gatherers IDs can be found at https://github.com/openshift/insights-operator/blob/master/docs/gathered-data.md.
                      Run the following command to get the names of last active gatherers:
                      "oc get insightsoperators.operator.openshift.io cluster -o json | jq '.status.gatherStatus.gatherers[].name'"
                      An example of disabling gatherers looks like this: `disabledGatherers: ["clusterconfig/machine_configs", "workloads/workload_info"]`
                    items:
                      maxLength: 256
                      type: string
                    maxItems: 100
                    type: array
                  storageSpec:
                    description: |-
                      storageSpec is an optional field that allows user to define persistent storage for on-demand gathering
                      jobs to store the Insights data archive.
                      If omitted, the gathering job will use ephemeral storage.
                    properties:
                      mountPath:
                        default: /var/lib/insights-operator
                        description: |-
                          mountPath is an optional field specifying the directory where the PVC will be mounted inside the
                          Insights data gathering Pod. If omitted, the path that is used to store the Insights data archive by Insights
                          operator will be used instead. The path cannot exceed 1024 characters and defaults to "/var/lib/insights-operator".
                        maxLength: 1024
                        type: string
                        x-kubernetes-validations:
                        - message: mountPath must not contain a colon
                          rule: '!self.contains('':'')'
                      persistentVolumeClaimName:
                        description: |-
                          persistentVolumeClaimName is required field that specifies the name of the PersistentVolumeClaim that will
                          be used to store the Insights data archive. The persistenVolumeClaim must be created in the openshift-insights namespace.
                        maxLength: 253
                        type: string
                        x-kubernetes-validations:
                        - message: a lowercase RFC 1123 subdomain must consist of
                            lower case alphanumeric characters, '-' or '.', and must
                            start and end with an alphanumeric character.
                          rule: '!format.dns1123Subdomain().validate(self).hasValue()'
                    required:
                    - persistentVolumeClaimName
                    type: object
                type: object
            type: object
          status:
            description: status holds observed values from the cluster. They may not
              be overridden.
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
